### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.4.0+

### ISSUE THREAD

**Issue by Neustradamus** [Syndace/python-omemo#32]
Can you update the XEP-0384: OMEMO Encryption support to 0.4.0+?
- https://xmpp.org/extensions/xep-0384.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

PS: Not sure that 0.3.0 was complete before:
- https://xmpp.org/extensions/attic/xep-0384-0.3.0.html

**Comment by Syndace** [comment]
The [stable branch](https://github.com/Syndace/python-omemo/tree/stable) together with the backend implementation [python-twomemo](https://github.com/Syndace/python-twomemo) implement OMEMO in the `urn:xmpp:omemo:2` namespace. This will soon be merged into the main branch.

**Comment by Neustradamus** [comment]
@Syndace: Thanks for your work!
What is the XEP-0384 supported version?

**Comment by Syndace** [comment]
Version 0.8.3 (the most recent version) and 0.3.0 for backward compatibility.

**Comment by Neustradamus** [comment]
@Syndace: Excellent! :)
