### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [Syndace/python-omemo#33]
@Syndace: Can you create a new build?

The last version is v0.11.0-beta:
- https://github.com/Syndace/python-omemo/releases
"Syndace released this on 13 Dec 2019 · 13 commits to master since this release"

**Comment by Neustradamus** [comment]
Linked to Debian 11 freeze:
- https://salsa.debian.org/xmpp-team/python-omemo-backend-signal

**Comment by Syndace** [comment]
Thanks for noting, I created a new release.
